// SECTION 1:
// Swarm Saw Start - James
// swarmSaw_1.scd


// StringRes1 Start - Robert
// time in:
   MeshMono.makeTemplate(\swarmSawJames, "_mono", "_bind");

// SwarmSaw end - james:
// time out:

// SECTION 2:
// StringRes 2 Start - Jason
// time in:

// FM Grain Starts - Robert
// time in:

// StringRes2 End - Jason
// time out:

// StringRes Ends - Robert

// SECTION 3: POLYRHYTHMIC
// Click starts - Robert
// time:




Synths:
